[package]
name = "pauropus"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
parking_lot = "0.12.0"
pin-project = "1.0.10"
